dist: trusty
language: python

python:
  - 2.7
  - 3.4
env:
  - TEST_SUITE=django
  - TEST_SUITE=lint

matrix:
  include:
    - python: 3.4
      env: TEST_SUITE=mypy
    - python: 3.4
      env: TEST_SUITE=futurize

install:
  - devel/travis/setup-$TEST_SUITE
script:
  - devel/travis/$TEST_SUITE
